name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests on PHP ${{ matrix.php }} and ${{ matrix.dependencies }} dependencies

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]
        dependencies: [lowest, highest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Execute tests
        run: vendor/bin/pest --colors=always

  code-style:
    name: Code style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --working-dir=tools/php-cs-fixer

      - name: Run php-cs-fixer
        run: composer cs-fix -- --dry-run --diff --using-cache=no --diff-format udiff
